name: Go format

on:
  pull_request:
    branches: [ '**' ]

jobs:
  goimports_diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: checkout
        uses: actions/checkout@v2

      - name: Format all .go files
        run:
          echo "Checking files:"
          find . -name '*.go'
          goimports -w $(find . -name '*.go')

      - name: Git diff
        run: git diff --exit-code
